In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Load the dataset again for safety
weather_df = pd.read_csv('weatherHistory.csv')

# Step 1: Select relevant columns
selected_cols = weather_df[['Summary', 'Precip Type', 'Temperature (C)', 'Humidity', 'Wind Speed (km/h)']].copy()

# Step 2: Convert continuous features to categorical bins
selected_cols['Temp Category'] = pd.cut(selected_cols['Temperature (C)'], bins=[-20, 5, 15, 30, 50], labels=['Cold', 'Cool', 'Warm', 'Hot'])
selected_cols['Humidity Category'] = pd.cut(selected_cols['Humidity'], bins=[0, 0.3, 0.6, 1.0], labels=['Low Humidity', 'Medium Humidity', 'High Humidity'])
selected_cols['Wind Category'] = pd.cut(selected_cols['Wind Speed (km/h)'], bins=[0, 10, 20, 100], labels=['Low Wind', 'Medium Wind', 'High Wind'])

# Step 3: Create transaction-like data
transactions = []
for _, row in selected_cols.iterrows():
    transaction = []
    if pd.notna(row['Summary']):
        transaction.append(f"Summary={row['Summary']}")
    if pd.notna(row['Precip Type']):
        transaction.append(f"Precip={row['Precip Type']}")
    if pd.notna(row['Temp Category']):
        transaction.append(f"Temp={row['Temp Category']}")
    if pd.notna(row['Humidity Category']):
        transaction.append(f"Humidity={row['Humidity Category']}")
    if pd.notna(row['Wind Category']):
        transaction.append(f"Wind={row['Wind Category']}")
    transactions.append(transaction)

# Step 4: Encode transactions
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_trans = pd.DataFrame(te_ary, columns=te.columns_)

# Step 5: Apply Apriori algorithm
frequent_itemsets = apriori(df_trans, min_support=0.05, use_colnames=True)

# Step 6: Generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
w
# Display top rules
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
148,"(Precip=snow, Wind=Low Wind)","(Humidity=High Humidity, Temp=Cold)",0.063223,0.982281,3.825102
52,(Precip=snow),"(Humidity=High Humidity, Temp=Cold)",0.107866,0.971247,3.782135
23,(Precip=snow),(Temp=Cold),0.110904,0.998600,3.752160
50,"(Humidity=High Humidity, Precip=snow)",(Temp=Cold),0.107866,0.998560,3.752012
105,"(Precip=snow, Wind=Low Wind)",(Temp=Cold),0.064218,0.997745,3.748948
146,"(Humidity=High Humidity, Precip=snow, Wind=Low...",(Temp=Cold),0.063223,0.997709,3.748814
58,(Summary=Foggy),"(Humidity=High Humidity, Temp=Cold)",0.055011,0.742306,2.890613
25,(Summary=Foggy),(Temp=Cold),0.055115,0.743705,2.794411
56,"(Humidity=High Humidity, Summary=Foggy)",(Temp=Cold),0.055011,0.743554,2.793845
155,"(Precip=rain, Wind=Low Wind, Humidity=Medium H...",(Temp=Warm),0.066374,0.735608,2.069104

In [ ]:
# Step 0: Install mlxtend if not already installed
# !pip install mlxtend

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Step 1: Load the dataset
weather_df = pd.read_csv("weatherHistory.csv")

# Step 2: Select relevant columns
selected_cols = weather_df[['Summary', 'Precip Type', 'Temperature (C)', 'Humidity', 'Wind Speed (km/h)']].copy()

# Step 3: Convert continuous values into categories
selected_cols['Temp Category'] = pd.cut(
    selected_cols['Temperature (C)'], bins=[-20, 5, 15, 30, 50],
    labels=['Cold', 'Cool', 'Warm', 'Hot'])

selected_cols['Humidity Category'] = pd.cut(
    selected_cols['Humidity'], bins=[0, 0.3, 0.6, 1.0],
    labels=['Low Humidity', 'Medium Humidity', 'High Humidity'])

selected_cols['Wind Category'] = pd.cut(
    selected_cols['Wind Speed (km/h)'], bins=[0, 10, 20, 100],
    labels=['Low Wind', 'Medium Wind', 'High Wind'])

# Step 4: Prepare transaction data
transactions = []
for _, row in selected_cols.iterrows():
    transaction = []
    if pd.notna(row['Summary']):
        transaction.append(f"Summary={row['Summary']}")
    if pd.notna(row['Precip Type']):
        transaction.append(f"Precip={row['Precip Type']}")
    if pd.notna(row['Temp Category']):
        transaction.append(f"Temp={row['Temp Category']}")
    if pd.notna(row['Humidity Category']):
        transaction.append(f"Humidity={row['Humidity Category']}")
    if pd.notna(row['Wind Category']):
        transaction.append(f"Wind={row['Wind Category']}")
    transactions.append(transaction)

# Step 5: Encode transactions
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_trans = pd.DataFrame(te_ary, columns=te.columns_)

# Step 6: Apply Apriori
frequent_itemsets = apriori(df_trans, min_support=0.05, use_colnames=True)

# Step 7: Generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

# Step 8: Display the best rules
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
148,"(Precip=snow, Wind=Low Wind)","(Humidity=High Humidity, Temp=Cold)",0.063223,0.982281,3.825102
52,(Precip=snow),"(Humidity=High Humidity, Temp=Cold)",0.107866,0.971247,3.782135
23,(Precip=snow),(Temp=Cold),0.110904,0.998600,3.752160
50,"(Humidity=High Humidity, Precip=snow)",(Temp=Cold),0.107866,0.998560,3.752012
105,"(Precip=snow, Wind=Low Wind)",(Temp=Cold),0.064218,0.997745,3.748948
146,"(Humidity=High Humidity, Precip=snow, Wind=Low...",(Temp=Cold),0.063223,0.997709,3.748814
58,(Summary=Foggy),"(Humidity=High Humidity, Temp=Cold)",0.055011,0.742306,2.890613
25,(Summary=Foggy),(Temp=Cold),0.055115,0.743705,2.794411
56,"(Humidity=High Humidity, Summary=Foggy)",(Temp=Cold),0.055011,0.743554,2.793845
155,"(Precip=rain, Wind=Low Wind, Humidity=Medium H...",(Temp=Warm),0.066374,0.735608,2.069104

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['support'].plot(kind='hist', bins=20, title='support')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['confidence'].plot(kind='hist', bins=20, title='confidence')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['lift'].plot(kind='hist', bins=20, title='lift')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('antecedents').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('consequents').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='index', y='support', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='support', y='confidence', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='confidence', y='lift', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['support'].plot(kind='line', figsize=(8, 4), title='support')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['confidence'].plot(kind='line', figsize=(8, 4), title='confidence')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['lift'].plot(kind='line', figsize=(8, 4), title='lift')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['consequents'].value_counts()
    for x_label, grp in _df_13.groupby('antecedents')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('antecedents')
_ = plt.ylabel('consequents')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['antecedents'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='index', y='antecedents', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['consequents'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='index', y='consequents', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['antecedents'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='support', y='antecedents', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['consequents'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='support', y='consequents', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)